import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Navigation from "@/Components/nav/page";
import Footer from "@/Components/footer/page";
import QueryProvider from "@/providers/QueryProvider";
import { ContextProvider } from "@/providers/ContextProvider";

export const metadata = {
  title: "Shopyfy Themes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log(process.env.THEME_API);

  return (
    <html lang="en" className="bg-white">
      <body>
        <NextUIProvider>
          <ContextProvider>
            <QueryProvider>
              <Navigation />
              {children}
              <Footer />
            </QueryProvider>
          </ContextProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
